"""App data store (D2: one relational store for everything user-visible).

Backends:
- Postgres when DATABASE_URL is set (Cloud Run + Cloud SQL) — durable.
  Same database the checkpointer and memory store already use.
- SQLite otherwise (local dev, tests) — zero-setup, zero-config.

Every query below is written once, in SQLite style ('?' placeholders and
portable ``ON CONFLICT`` upserts that both engines accept); the Postgres
adapter translates placeholders and the schema template swaps the
autoincrement idiom. Nothing user-visible may depend on container-local
disk: /tmp resets on every Cloud Run deploy or instance restart.

Lifecycle: api.py's lifespan calls initialize_storage() at startup (opens
the pool, waits for a connection, creates tables — a bad DATABASE_URL
fails the deploy, not the first user request) and close_storage() at
shutdown (psycopg guidance: pools are opened and closed with the app).

Schema management: this is BOOTSTRAP, not migration — CREATE TABLE IF NOT
EXISTS creates missing tables but can never add or alter columns on an
existing one. The first time a deployed table needs to change shape,
introduce Alembic (or numbered SQL migrations) and freeze this script as
migration 0001.

user_id flows via a contextvar set per-request in api.py — tools are called
by the LLM, which must never see or choose user identity.
"""
import sqlite3
from contextvars import ContextVar
from datetime import date
from functools import lru_cache

from vital.config import settings

current_user_id: ContextVar[str] = ContextVar("current_user_id", default="local-user")

# __ID__ expands to the dialect's autoincrementing integer primary key
_SCHEMA_TEMPLATE = """
CREATE TABLE IF NOT EXISTS sleep_logs (
    user_id TEXT, log_date TEXT, bedtime TEXT, wake_time TEXT,
    duration_min INTEGER, quality INTEGER,
    PRIMARY KEY (user_id, log_date)
);
CREATE TABLE IF NOT EXISTS health_sleep (
    user_id TEXT NOT NULL, date TEXT NOT NULL,
    duration_min INTEGER NOT NULL, quality TEXT, source TEXT,
    PRIMARY KEY (user_id, date)
);
CREATE TABLE IF NOT EXISTS interests (
    user_id TEXT, interest TEXT, PRIMARY KEY (user_id, interest)
);
CREATE TABLE IF NOT EXISTS ideas (
    user_id TEXT, idea TEXT, category TEXT, created TEXT
);
CREATE TABLE IF NOT EXISTS sandbox_runs (
    user_id TEXT, ts TEXT, ok INTEGER, error TEXT, code TEXT
);
CREATE TABLE IF NOT EXISTS committed_plans (
    user_id TEXT, plan_hash TEXT, PRIMARY KEY (user_id, plan_hash)
);
CREATE TABLE IF NOT EXISTS calendar_events (
    user_id TEXT, plan_hash TEXT, day TEXT, start TEXT, "end" TEXT,
    title TEXT, kind TEXT
);
CREATE TABLE IF NOT EXISTS token_usage (
    user_id TEXT, day TEXT, tokens INTEGER, PRIMARY KEY (user_id, day)
);
CREATE TABLE IF NOT EXISTS feedback (
    user_id TEXT, thread_id TEXT, ts TEXT, rating TEXT, comment TEXT
);
CREATE TABLE IF NOT EXISTS activity_posts (
    id __ID__,
    user_id TEXT NOT NULL, display_name TEXT NOT NULL,
    activity TEXT NOT NULL, city TEXT NOT NULL, area TEXT,
    time_window TEXT, vibe TEXT, skill_level TEXT, budget TEXT,
    group_size TEXT, notes TEXT, active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL, updated_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS activity_requests (
    id __ID__,
    post_id INTEGER NOT NULL, requester_user_id TEXT NOT NULL,
    requester_name TEXT, message TEXT,
    status TEXT NOT NULL DEFAULT 'pending',
    created_at TEXT NOT NULL, updated_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS user_blocks (
    user_id TEXT NOT NULL, blocked_key TEXT NOT NULL,
    created_at TEXT NOT NULL, PRIMARY KEY (user_id, blocked_key)
);
CREATE TABLE IF NOT EXISTS activity_reports (
    id __ID__,
    post_id INTEGER NOT NULL, reporter_user_id TEXT NOT NULL,
    reason TEXT, created_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS auth_identities (
    provider TEXT NOT NULL,
    subject TEXT NOT NULL,
    user_id TEXT NOT NULL UNIQUE,
    created_at TEXT NOT NULL,
    PRIMARY KEY (provider, subject)
);
CREATE TABLE IF NOT EXISTS user_threads (
    user_id TEXT NOT NULL,
    thread_id TEXT NOT NULL,
    title TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (user_id, thread_id)
);
"""


def schema_sql(dialect: str) -> str:
    pk = ("BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
          if dialect == "postgres" else "INTEGER PRIMARY KEY AUTOINCREMENT")
    return _SCHEMA_TEMPLATE.replace("__ID__", pk)


def pg_sql(sql: str) -> str:
    """SQLite-style '?' placeholders → psycopg '%s'. Our SQL never contains
    a literal question mark, so plain replace is safe."""
    return sql.replace("?", "%s")


class _SqliteConn:
    """Context manager: commit on success, rollback on error, always close."""

    def __init__(self, path: str):
        self.raw = sqlite3.connect(path)
        self.raw.executescript(schema_sql("sqlite"))
        self.raw.row_factory = sqlite3.Row

    def execute(self, sql: str, params=()):
        return self.raw.execute(sql, params)

    def executemany(self, sql: str, seq) -> None:
        self.raw.executemany(sql, seq)

    def insert_id(self, sql: str, params=()) -> int:
        return self.raw.execute(sql, params).lastrowid

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, tb):
        if exc_type is None:
            self.raw.commit()
        else:
            self.raw.rollback()
        self.raw.close()


class _PgConn:
    """Same interface over a pooled psycopg connection. The pool's context
    manager commits/rolls back and returns the connection."""

    def __init__(self, pool):
        self._cm = pool.connection()

    def execute(self, sql: str, params=()):
        # params=None skips psycopg's placeholder parsing entirely — needed
        # for parameterless SQL containing literal '%' (e.g. LIKE patterns)
        return self.raw.execute(pg_sql(sql), params or None)

    def executemany(self, sql: str, seq) -> None:
        with self.raw.cursor() as cur:
            cur.executemany(pg_sql(sql), list(seq))

    def insert_id(self, sql: str, params=()) -> int:
        row = self.raw.execute(pg_sql(sql) + " RETURNING id", params).fetchone()
        return int(row["id"])

    def __enter__(self):
        self.raw = self._cm.__enter__()
        return self

    def __exit__(self, exc_type, exc, tb):
        return self._cm.__exit__(exc_type, exc, tb)


@lru_cache
def _pg_pool(conninfo: str):
    """One pool per process; verifies connectivity and creates the app
    tables before anyone gets a connection. psycopg's extended protocol
    runs one statement per execute, so the schema script is split on ';'."""
    from psycopg.rows import dict_row
    from psycopg_pool import ConnectionPool

    pool = ConnectionPool(conninfo, min_size=1, max_size=10, open=True,
                          kwargs={"row_factory": dict_row})
    try:
        pool.wait(timeout=15)  # raises PoolTimeout if the DB is unreachable
        with pool.connection() as conn:
            for stmt in schema_sql("postgres").split(";"):
                if stmt.strip():
                    conn.execute(stmt)
    except Exception:
        pool.close()
        _pg_pool.cache_clear()  # don't cache a broken pool
        raise
    return pool


def _conn():
    cfg = settings()
    if cfg.database_url:
        return _PgConn(_pg_pool(cfg.database_url))
    return _SqliteConn(cfg.sqlite_path)


def initialize_storage() -> None:
    """Called from the API lifespan at startup. Opens the Postgres pool,
    waits for a live connection, and creates the schema — so a bad or
    unreachable DATABASE_URL fails the deploy immediately instead of
    surfacing on the first user request. On SQLite it touches the file,
    proving the path is writable."""
    cfg = settings()
    if cfg.database_url:
        _pg_pool(cfg.database_url)
    else:
        with _conn():
            pass


def close_storage() -> None:
    """Called from the API lifespan at shutdown; closes the pool cleanly
    (SQLite connections are per-call, so there is nothing to close)."""
    cfg = settings()
    if cfg.database_url and _pg_pool.cache_info().currsize:
        _pg_pool(cfg.database_url).close()
        _pg_pool.cache_clear()


# ---------- external auth identities (Firebase Google Sign-In) ----------
# 'subject' is the Firebase UID (never email). Everything else in the app
# keys off the INTERNAL user_id, so no other table changes shape.

def resolve_external_identity(provider: str, subject: str,
                              candidate_anonymous_user_id: str | None) -> str:
    """Stable internal user_id for an external (provider, subject).

    - Existing mapping → its stored user_id.
    - First sign-in → claims the server-resolved anonymous identity (so the
      browser's pre-sign-in data follows the account), unless that identity
      is already claimed by some other subject; otherwise a fresh internal
      id is minted. The candidate is server-derived — clients never pick it.
    - Concurrency-safe: UNIQUE(user_id) makes a double-claim impossible at
      the database level; the claim INSERT uses a TARGETLESS
      ``ON CONFLICT DO NOTHING`` so losing either race — same (provider,
      subject) inserted twice, or the candidate user_id taken by another
      subject a microsecond earlier — is silently absorbed, and the read
      back decides what actually happened. Two subjects racing for one
      anonymous identity: exactly one wins it, the other gets a fresh id.
    """
    from datetime import datetime, timezone
    import uuid as _uuid

    now = datetime.now(timezone.utc).isoformat()
    with _conn() as c:
        row = c.execute("SELECT user_id FROM auth_identities "
                        "WHERE provider = ? AND subject = ?",
                        (provider, subject)).fetchone()
        if row:
            return row["user_id"]
        if candidate_anonymous_user_id:
            # the WHERE NOT EXISTS guard skips obviously-taken candidates;
            # the unique index + targetless DO NOTHING handles the raced case
            c.execute(
                """INSERT INTO auth_identities (provider, subject, user_id, created_at)
                   SELECT ?, ?, ?, ?
                   WHERE NOT EXISTS (SELECT 1 FROM auth_identities WHERE user_id = ?)
                   ON CONFLICT DO NOTHING""",
                (provider, subject, candidate_anonymous_user_id, now,
                 candidate_anonymous_user_id))
        row = c.execute("SELECT user_id FROM auth_identities "
                        "WHERE provider = ? AND subject = ?",
                        (provider, subject)).fetchone()
        if row:
            return row["user_id"]
        fresh = f"usr-{_uuid.uuid4().hex}"
        c.execute("INSERT INTO auth_identities VALUES (?, ?, ?, ?) "
                  "ON CONFLICT DO NOTHING",
                  (provider, subject, fresh, now))
        row = c.execute("SELECT user_id FROM auth_identities "
                        "WHERE provider = ? AND subject = ?",
                        (provider, subject)).fetchone()
        return row["user_id"]


def user_id_is_linked(user_id: str) -> bool:
    """True if this internal id belongs to a signed-in account — an
    anonymous session must never keep resolving to it (see security.py)."""
    with _conn() as c:
        row = c.execute("SELECT 1 FROM auth_identities WHERE user_id = ?",
                        (user_id,)).fetchone()
    return row is not None


# ---------- user thread index (cross-device thread list for signed-in users;
# ---------- messages themselves live in the checkpointer) ----------

def upsert_user_thread(user_id: str, thread_id: str, title_hint: str) -> None:
    """Insert keeps the first title; later messages only bump updated_at."""
    from datetime import datetime, timezone
    now = datetime.now(timezone.utc).isoformat()
    title = " ".join(title_hint.split())[:60] or "New chat"
    with _conn() as c:
        c.execute(
            """INSERT INTO user_threads VALUES (?, ?, ?, ?, ?)
               ON CONFLICT (user_id, thread_id) DO UPDATE SET
                 updated_at = excluded.updated_at""",
            (user_id, thread_id, title, now, now))


def delete_user_thread(user_id: str, thread_id: str) -> None:
    """Removes ONE row from the caller's own sidebar index. This UNLISTS
    the thread — checkpointer conversation state is not touched, and the
    thread reappears only if the user chats on the same id again."""
    with _conn() as c:
        c.execute("DELETE FROM user_threads WHERE user_id = ? AND thread_id = ?",
                  (user_id, thread_id))


def user_threads(user_id: str, limit: int = 100) -> list[dict]:
    with _conn() as c:
        rows = c.execute(
            "SELECT thread_id, title, created_at, updated_at FROM user_threads "
            "WHERE user_id = ? ORDER BY updated_at DESC LIMIT ?",
            (user_id, limit)).fetchall()
    return [dict(r) for r in rows]


def compute_duration_min(bedtime: str, wake_time: str) -> int:
    """Duration from 'HH:MM' strings, handling the cross-midnight case.
    Computed HERE, not by the LLM — models are unreliable at time arithmetic."""
    from datetime import datetime, timedelta
    bed = datetime.strptime(bedtime, "%H:%M")
    wake = datetime.strptime(wake_time, "%H:%M")
    if wake <= bed:
        wake += timedelta(days=1)
    return int((wake - bed).total_seconds() // 60)


def log_sleep(bedtime: str, wake_time: str, quality: int) -> int:
    """Validates and stores; returns computed duration_min.
    Raises ValueError on impossible input — the tool layer turns that into
    a message the model can use to re-ask the user."""
    if not 1 <= quality <= 5:
        raise ValueError(f"quality must be 1-5, got {quality}")
    duration_min = compute_duration_min(bedtime, wake_time)  # raises on bad HH:MM
    if not 30 <= duration_min <= 18 * 60:
        raise ValueError(f"implausible sleep duration: {duration_min} min")
    with _conn() as c:
        c.execute(
            """INSERT INTO sleep_logs VALUES (?, ?, ?, ?, ?, ?)
               ON CONFLICT (user_id, log_date) DO UPDATE SET
                 bedtime = excluded.bedtime, wake_time = excluded.wake_time,
                 duration_min = excluded.duration_min, quality = excluded.quality""",
            (current_user_id.get(), date.today().isoformat(), bedtime, wake_time,
             duration_min, quality),
        )
    return duration_min


def sleep_history(days: int) -> list[dict]:
    with _conn() as c:
        rows = c.execute(
            "SELECT * FROM sleep_logs WHERE user_id = ? ORDER BY log_date DESC LIMIT ?",
            (current_user_id.get(), days),
        ).fetchall()
    return [dict(r) for r in rows]


# ---------- uploaded health data (was per-user CSV files on local disk;
# ---------- container disk is ephemeral, so rows live in the database) ----------

def save_health_rows(user_id: str, rows: list[dict]) -> int:
    """Merge-by-date upsert (new upload wins on conflicts). Returns #rows."""
    with _conn() as c:
        c.executemany(
            """INSERT INTO health_sleep VALUES (?, ?, ?, ?, ?)
               ON CONFLICT (user_id, date) DO UPDATE SET
                 duration_min = excluded.duration_min,
                 quality = excluded.quality, source = excluded.source""",
            [(user_id, r["date"], int(r["duration_min"]),
              str(r.get("quality") or ""), str(r.get("source") or "upload"))
             for r in rows])
    return len(rows)


def health_rows(user_id: str) -> list[dict]:
    with _conn() as c:
        rows = c.execute(
            "SELECT date, duration_min, quality, source FROM health_sleep "
            "WHERE user_id = ? ORDER BY date", (user_id,)).fetchall()
    return [dict(r) for r in rows]


def add_interest(interest: str) -> None:
    with _conn() as c:
        c.execute("INSERT INTO interests VALUES (?, ?) "
                  "ON CONFLICT (user_id, interest) DO NOTHING",
                  (current_user_id.get(), interest.lower()))


def interests() -> list[str]:
    with _conn() as c:
        rows = c.execute("SELECT interest FROM interests WHERE user_id = ?",
                         (current_user_id.get(),)).fetchall()
    return [r["interest"] for r in rows]


def save_idea(idea: str, category: str) -> None:
    with _conn() as c:
        c.execute("INSERT INTO ideas VALUES (?, ?, ?, ?)",
                  (current_user_id.get(), idea, category, date.today().isoformat()))


def log_sandbox_run(code: str, ok: bool, error: str | None) -> None:
    """Audit trail: every snippet of generated code that reached the
    execution gate, per user, with outcome (Phase 2 safety rail)."""
    from datetime import datetime, timezone
    with _conn() as c:
        c.execute("INSERT INTO sandbox_runs VALUES (?, ?, ?, ?, ?)",
                  (current_user_id.get(), datetime.now(timezone.utc).isoformat(),
                   int(ok), error, code))


def sandbox_audit(limit: int = 50) -> list[dict]:
    with _conn() as c:
        rows = c.execute(
            "SELECT ts, ok, error, code FROM sandbox_runs WHERE user_id = ? "
            "ORDER BY ts DESC LIMIT ?", (current_user_id.get(), limit)).fetchall()
    return [dict(r) for r in rows]


def save_feedback(user_id: str, thread_id: str, rating: str, comment: str) -> None:
    from datetime import datetime, timezone
    with _conn() as c:
        c.execute("INSERT INTO feedback VALUES (?, ?, ?, ?, ?)",
                  (user_id, thread_id, datetime.now(timezone.utc).isoformat(),
                   rating, comment))


def feedback_summary() -> dict:
    """Phase 5 iteration loop: thumbs by day. (Per-user data stays private.)"""
    with _conn() as c:
        rows = c.execute("""SELECT substr(ts, 1, 10) AS day, rating, COUNT(*) AS n
                            FROM feedback GROUP BY day, rating ORDER BY day DESC""").fetchall()
    return {"by_day": [dict(r) for r in rows]}


def add_tokens(user_id: str, tokens: int) -> None:
    with _conn() as c:
        c.execute("""INSERT INTO token_usage VALUES (?, ?, ?)
                     ON CONFLICT (user_id, day) DO UPDATE SET
                       tokens = token_usage.tokens + excluded.tokens""",
                  (user_id, date.today().isoformat(), tokens))


def tokens_used_today(user_id: str) -> int:
    with _conn() as c:
        row = c.execute("SELECT tokens FROM token_usage WHERE user_id = ? AND day = ?",
                        (user_id, date.today().isoformat())).fetchone()
    return row["tokens"] if row else 0


def plan_already_committed(user_id: str, plan_hash: str) -> bool:
    with _conn() as c:
        row = c.execute("SELECT 1 FROM committed_plans WHERE user_id = ? AND plan_hash = ?",
                        (user_id, plan_hash)).fetchone()
    return row is not None


def save_calendar_events(user_id: str, plan_hash: str, items: list[dict]) -> None:
    """Marker + events in ONE transaction — a crash can't leave the hash
    recorded with the events missing (or vice versa)."""
    with _conn() as c:
        c.execute("INSERT INTO committed_plans VALUES (?, ?)", (user_id, plan_hash))
        c.executemany(
            "INSERT INTO calendar_events VALUES (?, ?, ?, ?, ?, ?, ?)",
            [(user_id, plan_hash, i["day"], i["start"], i["end"], i["title"], i["kind"])
             for i in items])


def calendar_events(user_id: str) -> list[dict]:
    with _conn() as c:
        rows = c.execute("SELECT day, start, \"end\", title, kind FROM calendar_events "
                         "WHERE user_id = ?", (user_id,)).fetchall()
    return [dict(r) for r in rows]


def saved_ideas() -> list[dict]:
    with _conn() as c:
        rows = c.execute("SELECT idea, category, created FROM ideas WHERE user_id = ?",
                         (current_user_id.get(),)).fetchall()
    return [dict(r) for r in rows]
