"""Postgres migration guards.

Layer 1 (always runs): the schema renders correctly for both dialects,
placeholder translation is sound, and no module has slipped back into
SQLite-only SQL (INSERT OR REPLACE/IGNORE, lastrowid).

Layer 2 (opt-in): a full round-trip through storage + buddies + ingest
against a real Postgres. Set VITAL_TEST_DATABASE_URL to run, e.g.
    VITAL_TEST_DATABASE_URL=postgresql://localhost/vital_test pytest
Skipped otherwise so CI/local runs stay dependency-free.
"""
import inspect
import os

os.environ.setdefault("GOOGLE_CLOUD_PROJECT", "test")
os.environ.setdefault("OPENWEATHER_API_KEY", "test")
os.environ.setdefault("GOOGLE_PLACES_API_KEY", "test")

import pytest

from vital import buddies, storage

# ---------- Layer 1: dialect hygiene (no database needed) ----------

def test_schema_renders_for_both_dialects():
    pg = storage.schema_sql("postgres")
    lite = storage.schema_sql("sqlite")
    assert "GENERATED BY DEFAULT AS IDENTITY" in pg
    assert "AUTOINCREMENT" not in pg
    assert "AUTOINCREMENT" in lite
    assert "IDENTITY" not in lite
    assert "__ID__" not in pg and "__ID__" not in lite
    # every user-visible table exists in the shared schema
    for table in ("sleep_logs", "health_sleep", "feedback", "calendar_events",
                  "token_usage", "activity_posts", "activity_requests",
                  "user_blocks", "activity_reports"):
        assert f"CREATE TABLE IF NOT EXISTS {table}" in pg


def test_placeholder_translation():
    assert storage.pg_sql("INSERT INTO t VALUES (?, ?, ?)") == \
        "INSERT INTO t VALUES (%s, %s, %s)"
    assert storage.pg_sql("SELECT 1") == "SELECT 1"


def test_no_sqlite_only_sql_in_data_modules():
    """Regression guard: portable upserts only. 'INSERT OR ...' and
    lastrowid are SQLite-isms that silently break on Postgres."""
    for module in (storage, buddies):
        src = inspect.getsource(module)
        assert "INSERT OR " not in src, f"{module.__name__} uses SQLite-only upsert"
        assert "lastrowid" not in src or module is storage, \
            f"{module.__name__} must use the adapter's insert_id()"


def test_initialize_and_close_storage_on_sqlite():
    # SQLite path: initialize touches the DB file, close is a no-op
    storage.initialize_storage()
    storage.close_storage()
    assert storage.tokens_used_today("nobody") == 0  # store still usable


# ---------- lifespan owns the pool: behavioral tests ----------

def _run_lifespan(api, expect: type[Exception]):
    import asyncio

    async def run():
        with pytest.raises(expect):
            async with api.lifespan(api.app):
                pass
    asyncio.run(run())


def test_storage_closes_when_graph_build_fails(monkeypatch):
    """Startup order is initialize_storage() → build_graph_async(); a graph
    failure must still close the pool the storage init just opened."""
    pytest.importorskip("langchain_google_vertexai")
    import vital.api as api

    calls = []
    monkeypatch.setattr(api, "initialize_storage", lambda: calls.append("init"))
    monkeypatch.setattr(api, "close_storage", lambda: calls.append("close"))

    async def boom():
        raise RuntimeError("graph build failed")
    monkeypatch.setattr(api, "build_graph_async", boom)

    _run_lifespan(api, RuntimeError)
    assert calls == ["init", "close"]


def test_storage_closes_when_graph_cleanup_raises(monkeypatch):
    """Shutdown: close_graph_resources() raising must not skip close_storage()
    (nested finally), and the error still propagates."""
    pytest.importorskip("langchain_google_vertexai")
    import vital.api as api

    closed = []
    monkeypatch.setattr(api, "initialize_storage", lambda: None)
    monkeypatch.setattr(api, "close_storage", lambda: closed.append(True))

    async def fake_build():
        return object()

    async def bad_close():
        raise RuntimeError("graph cleanup exploded")
    monkeypatch.setattr(api, "build_graph_async", fake_build)
    monkeypatch.setattr(api, "close_graph_resources", bad_close)

    _run_lifespan(api, RuntimeError)
    assert closed == [True]
    api.graph = None  # don't leak the fake graph into other tests


# ---------- Layer 2: live Postgres round-trip (opt-in) ----------

LIVE_URL = os.environ.get("VITAL_TEST_DATABASE_URL")


@pytest.mark.skipif(not LIVE_URL, reason="set VITAL_TEST_DATABASE_URL to run")
def test_live_postgres_round_trip(monkeypatch):
    from vital import ingest
    from vital.config import settings

    monkeypatch.setenv("DATABASE_URL", LIVE_URL)
    settings.cache_clear()
    storage._pg_pool.cache_clear()
    storage.initialize_storage()   # what the API lifespan runs at startup
    try:
        # app tables: manual log, upload merge, usage counter, feedback
        storage.current_user_id.set("pg-test-user")
        assert storage.log_sleep("23:00", "07:00", 4) == 480
        assert storage.sleep_history(1)[0]["duration_min"] == 480
        ingest.save_sleep_data("pg-test-user", [
            {"date": "2026-07-01", "duration_min": 400, "quality": "", "source": "csv_upload"}])
        ingest.save_sleep_data("pg-test-user", [
            {"date": "2026-07-01", "duration_min": 410, "quality": "3", "source": "apple_health"}])
        rows = storage.health_rows("pg-test-user")
        assert [r["duration_min"] for r in rows] == [410]   # merge-by-date
        storage.add_tokens("pg-test-user", 100)
        storage.add_tokens("pg-test-user", 50)
        assert storage.tokens_used_today("pg-test-user") == 150

        # calendar: "end" is a reserved word in Postgres — must stay quoted
        storage.save_calendar_events("pg-test-user", "hash1", [
            {"day": "Sat", "start": "10:00", "end": "11:00",
             "title": "Swim", "kind": "activity"}])
        (event,) = storage.calendar_events("pg-test-user")
        assert event["end"] == "11:00" and event["title"] == "Swim"
        assert storage.plan_already_committed("pg-test-user", "hash1")

        # feedback + substr() day aggregation
        storage.save_feedback("pg-test-user", "t1", "up", "")
        assert any(d["n"] >= 1 for d in storage.feedback_summary()["by_day"])

        # buddy board: create → search → request → decide → block
        post = buddies.create_post("pg-owner", {
            "display_name": "Swim Sam", "activity": "swimming", "city": "Albany"})
        assert post["id"] and post["mine"]
        found = buddies.search_posts("pg-seeker", activity="swimming")
        assert any(p["id"] == post["id"] for p in found)
        req = buddies.create_request("pg-seeker", post["id"], "hi")
        assert buddies.decide_request("pg-owner", req["id"], "accepted")["status"] == "accepted"
        buddies.block_user("pg-seeker", post["owner_key"])
        assert buddies.search_posts("pg-seeker", activity="swimming") == []
    finally:
        # scrub test rows so reruns stay deterministic
        with storage._conn() as c:
            for table, col in (("sleep_logs", "user_id"), ("health_sleep", "user_id"),
                               ("token_usage", "user_id"), ("user_blocks", "user_id"),
                               ("calendar_events", "user_id"),
                               ("committed_plans", "user_id"), ("feedback", "user_id")):
                c.execute(f"DELETE FROM {table} WHERE {col} LIKE 'pg-%'")
            c.execute("DELETE FROM activity_requests WHERE requester_user_id LIKE 'pg-%'")
            c.execute("DELETE FROM activity_posts WHERE user_id LIKE 'pg-%'")
        storage.close_storage()    # what the API lifespan runs at shutdown
        settings.cache_clear()
